#ifndef _LEXICAL_
#define _LEXICAL_

#include <stdio.h>

extern int yylex ( void );
//int returnToken ( int tk );

#define	TK_NAME	yyname /* Using the names generated by Yacc */

#define ASCII_OFFSET 257

#define INTEGER 4
#define HEXADECIMAL 5
#define FLOAT 6

#define TK_EOF -1

extern const char* const TK_NAME[];

typedef struct Info_t {
	long int i;
	double f;
	char*s;
} Info_t;

extern Info_t info;

#endif
